version: "3.7"

services:
    frontend:
        build: ./frontend
        ports: 
            - 8080:5000
        links:
            - backend

    backend:
        build: ./backend
        ports: 
            - 5000:5000

    