# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Unit Tests 

on:
  push:
  pull_request:
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3   
      env:
        BACKEND-URL: ${{secrets.BACKEND_URL}}
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - run: echo $'const apiUrl = "$BACKEND-URL"\n\nexport default apiUrl' > config.js
      working-directory: './frontend'
    - run: npm ci
      working-directory: './frontend'
    - run: npm run test:unit
      working-directory: './frontend'